### ISSUE TITLE
hAP lite

### ISSUE THREAD

**Issue by vahid67** [belykhk/mikrotik-ovpn-client-tls-crypt#2]
Hello,
I'm completely new to MikroTik platform, I just recently purchased a hAP lite to provide VPN to all my devices. 
I upgraded its software to v7.17.1.
I want to know if this works with that device?

I used this script to run the server and it works great using the open VPN client application.
https://github.com/Angristan/openvpn-install

Do I need to run the command you mentioned inside the MikroTik or my current open VPN server? A detailed tutorial would be great.

**Comment by belykhk** [comment]
Hello.

If you are fully control VPN server and want to use it with router -- I'd recommend you to recreate your VPN installation (or create one without TLS crypt as additional service) and use native OpenVPN client in router, since container in my repo will be a lot slower than native client.

As far as detailed tutorial -- it is intended not to have one, since everyone installation differs and has different needs. There is a link to documentation on Mikrotik KB to get yourself familiar with containers on Mikrotik, but I probably wouldn't want to run them on Hap Lite, since he didn't have powerful CPU.
